---
- name: PHP
  hosts: phone-book
  become: true
  tasks:
    - name: PHP | Install php fpm
      apt: name=php7.4-fpm state=latest

    - name: PHP | Start php fpm service
      shell:
        cmd: /etc/init.d/php7.4-fpm start