---
- name: PHP
  hosts: phone-book
  become: true
  tasks:
    - name: PHP | Install php fpm
      apt: name=php7.3-fpm state=latest force=yes

    - name: PHP | Install php phalcon
      apt: name=php-phalcon state=latest force=yes

    - name: PHP | Install mysql client module
      apt: name=php7.3-mysql state=latest force=yes

    - name: PHP | Install zip module
      apt: name=php7.3-zip state=latest force=yes

    - name: PHP | Install memcached module
      apt: name=php-memcached state=latest force=yes

    - name: PHP | Install ext-dom module
      apt: name=php7.3-xml state=latest force=yes

    - name: PHP | Install mbstring module
      apt: name=php7.3-mbstring state=latest force=yes

    - name: PHP | Copy php-fpm php.ini configuration
      copy:
        src: ../../templates/php/fpm/php.ini
        dest: /etc/php/7.3/fpm

    - name: PHP | Copy php-fpm.conf configuration
      copy:
        src: ../../templates/php/fpm/php-fpm.conf
        dest: /etc/php/7.3/fpm

    - name: PHP | Copy php-fpm.conf configuration
      copy:
        src: ../../templates/php/fpm/pool.d/www.conf
        dest: /etc/php/7.3/fpm/pool.d

    - name: PHP | Restart php fpm service
      shell:
        cmd: /etc/init.d/php7.3-fpm restart

    - name: PHP | Composer Donwload composer installer
      shell:
        cmd: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

    - name: PHP | Composer Verify installer
      shell:
        cmd: php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

    - name: PHP | Composer Run the installer
      shell:
        cmd: php composer-setup.php

    - name: PHP | Composer Remove the installer
      shell:
        cmd: php -r "unlink('composer-setup.php');"

    - name: PHP | Composer Install composer globally
      shell:
        cmd: mv /home/vagrant/composer.phar /usr/local/bin/composer