---
- name: PHP
  hosts: phone-book
  become: true
  tasks:
    - name: PHP | Install php fpm
      apt: name=php7.4-fpm state=latest

    - name: PHP | Copy php.ini configuration
      copy:
        src: ../../templates/php/fpm/php.ini
        dest: /etc/php/7.4/fpm

    - name: PHP | Copy php-fpm.conf configuration
      copy:
        src: ../../templates/php/fpm/php-fpm.conf
        dest: /etc/php/7.4/fpm

    - name: PHP | Start php fpm service
      shell:
        cmd: /etc/init.d/php7.4-fpm start