---
- name: MYSQL
  hosts: phone-book
  become: true
  tasks:
    - name: MYSQL | Install mysql server
      apt: name=mysql-server state=latest force=yes

    - name: MYSQL | Change root user password
      shell:
        cmd: sudo mysql -e "FLUSH PRIVILEGES;SET PASSWORD FOR 'root'@'localhost' = PASSWORD('toor');"

    - name: MYSQL | Create hostaway user
      shell:
        cmd: sudo mysql -u root -ptoor -e "GRANT ALL PRIVILEGES ON *.* TO 'hostaway'@'localhost' IDENTIFIED BY 'hostaway'"

    - name: MYSQL | Copy phone-book sql script to create tables and data bases
      copy:
        src: ../../templates/mysql/phone-book.sql
        dest: /usr/local/etc/

    - name: MYSQL | Create hostaway data base and phone-book table
        shell:
          cmd: sudo mysql -u hostaway -phostaway < /usr/local/etc/phone-book.sql
