---
- name: MYSQL
  hosts: phone-book
  become: true
  tasks:
    - name: MYSQL | Install mysql server
      apt: name=mysql-server state=latest force=yes

    - name: MYSQL | Create hostaway user
      shell:
        cmd: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'hostaway'@'localhost' IDENTIFIED BY 'hostaway'"

    - name: MYSQL | Copy phone-book sql script to create database and tables
      copy:
        src: ../../templates/mysql/phone-book.sql
        dest: /usr/local/etc/

    - name: MYSQL | Create hostaway data base and phone-book table
      shell:
        cmd: mysql -u hostaway -phostaway < /usr/local/etc/phone-book.sql
